apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/moneyflow-pod/
patchesStrategicMerge:
- ./kind-moneyflow-patch.yaml
images:
- name: moneyflow-api-image
  newName: moneyflow-api-amd64
  newTag: "1.0"
